apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: trading
    user: trading
    secureJsonData:
      password: trading
    jsonData:
      sslmode: "disable"
      postgresVersion: 15
      timescaledb: true
    isDefault: true
